#!/bin/sh

# This runs automatically when you run sx to start the graphical environment.

# Determine the statusbar.
export STATUSBAR="dwmblocks"

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in xprofile because that
# file is run automatically if someone uses a display manager (login screen)
# and so they are needed there. To prevent doubling up commands, I source them
# here with the line below.
[ -f "$XDG_CONFIG_HOME/x11/xprofile" ] && ."$XDG_CONFIG_HOME/x11/xprofile"

while :; do
	exec dwm
done
